//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buying_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKING_HOURS
    {
        public int SHOP_ID { get; set; }
        public int DAY_OF_WEK_ID { get; set; }
        public System.TimeSpan OPEN_TIME { get; set; }
        public System.TimeSpan CLOSE_TIME { get; set; }
    
        public virtual SHOP SHOP { get; set; }
        public virtual WEEK_DAYS WEEK_DAYS { get; set; }
    }
}
